version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/learning-mate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${secrets.MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${secrets.MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: learning-mate
    ports:
      - "3306:3306"

volumes:
  mysql-data:
