version: '3.8'
services:
  blue:
    image: kabyho3513/learning-mate:1.0.0
    container_name: blue
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - db
      - redis
  green:
    image: kabyho3513/learning-mate:1.0.0
    container_name: green
    ports:
      - "8082:8080"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: learning-mate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $${secrets.MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: learning-mate
      MYSQL_USER: kang
      MYSQL_PASSWORD: $${secrets.MYSQL_KANG_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    container_name: learning-mate-redis
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/learning-mate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $${secrets.MYSQL_ROOT_PASSWORD}

volumes:
  mysql-data:
  redis-data: