version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  blue:
    image: kabyho3513/learning-mate-server:1.0.0
    container_name: blue
    expose:
      - "8082:8081"
    depends_on:
      - redis
      - mysql

  green:
    image: kabyho3513/learning-mate-server:1.0.0
    container_name: green
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql:latest
    container_name: learning-mate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: learning-mate
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: learning-mate-redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
